version: '3.1'
services:
  darkness:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: darkness
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:80
    environment:
      - DOMAIN_NAME=https://darkness.ukasz.com
