version: '3.1'
services:
  darkness:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: darkness
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - 8080:80
