# Generated by Django 4.1.7 on 2023-02-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('g', 'g'), ('h', 'h'), ('i', 'i'), ('j', 'j'), ('k', 'k'), ('l', 'l'), ('ł', 'ł'), ('m', 'm'), ('n', 'n'), ('o', 'o'), ('p', 'p'), ('r', 'r'), ('s', 's'), ('t', 't'), ('u', 'u'), ('w', 'w'), ('z', 'z')], max_length=1)),
                ('second', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('g', 'g'), ('h', 'h'), ('i', 'i'), ('j', 'j'), ('k', 'k'), ('l', 'l'), ('ł', 'ł'), ('m', 'm'), ('n', 'n'), ('o', 'o'), ('p', 'p'), ('r', 'r'), ('s', 's'), ('t', 't'), ('u', 'u'), ('w', 'w'), ('z', 'z')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.pair')),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='best',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abc', to='core.word'),
        ),
    ]
