# Generated by Django 4.1.7 on 2023-02-15 15:34

import json

from django.db import migrations


def import_data(apps, schema_editor):
    Pair = apps.get_model('core', 'Pair')
    Word = apps.get_model('core', 'Word')

    with open('data.json') as f:
        data = json.load(f)

    for pair_letters, pair_data in data.items():
        pair = Pair(first=pair_letters[0], second=pair_letters[1])
        pair.save()

        for word_text in pair_data['all']:
            word = Word(pair=pair, word=word_text)
            word.save()

            if word_text == pair_data['best']:
                pair.best = word
                pair.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data),
    ]
