# Generated by Django 5.2 on 2025-05-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='difficult',
            field=models.BooleanField(default=False, help_text='Difficult to remember'),
        ),
    ]
