# Generated by Django 4.1.7 on 2023-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Edge'), (2, 'Corner')])),
                ('faces', models.ManyToManyField(to='core.face')),
            ],
        ),
    ]
