# Generated by Django 4.1.7 on 2023-02-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=1)),
                ('second', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('best', models.BooleanField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='Words.pair')),
            ],
        ),
    ]
